// ─── country_data.dart ───────────────────────────────────────────────────────

// ─── OTP Channel Enum ────────────────────────────────────────────────────────

enum OtpChannel { whatsapp, sms }

// ─── Country Model ───────────────────────────────────────────────────────────

class Country {
  final String name;
  final String code;
  final String dialCode;
  final int phoneLength;
  final String flag; // emoji flag

  const Country({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.phoneLength,
    required this.flag,
  });
}

// Helper: converts ISO country code to flag emoji
String flagEmoji(String isoCode) {
  return isoCode.toUpperCase().split('').map((c) {
    return String.fromCharCode(c.codeUnitAt(0) + 127397);
  }).join();
}

// ─── Full Country List ───────────────────────────────────────────────────────

final List<Country> kCountries = [
  Country(name: 'Afghanistan',              code: 'AF', dialCode: '+93',  phoneLength: 9,  flag: flagEmoji('AF')),
  Country(name: 'Albania',                  code: 'AL', dialCode: '+355', phoneLength: 9,  flag: flagEmoji('AL')),
  Country(name: 'Algeria',                  code: 'DZ', dialCode: '+213', phoneLength: 9,  flag: flagEmoji('DZ')),
  Country(name: 'Andorra',                  code: 'AD', dialCode: '+376', phoneLength: 6,  flag: flagEmoji('AD')),
  Country(name: 'Angola',                   code: 'AO', dialCode: '+244', phoneLength: 9,  flag: flagEmoji('AO')),
  Country(name: 'Argentina',                code: 'AR', dialCode: '+54',  phoneLength: 10, flag: flagEmoji('AR')),
  Country(name: 'Armenia',                  code: 'AM', dialCode: '+374', phoneLength: 8,  flag: flagEmoji('AM')),
  Country(name: 'Australia',                code: 'AU', dialCode: '+61',  phoneLength: 9,  flag: flagEmoji('AU')),
  Country(name: 'Austria',                  code: 'AT', dialCode: '+43',  phoneLength: 10, flag: flagEmoji('AT')),
  Country(name: 'Azerbaijan',               code: 'AZ', dialCode: '+994', phoneLength: 9,  flag: flagEmoji('AZ')),
  Country(name: 'Bahamas',                  code: 'BS', dialCode: '+1',   phoneLength: 10, flag: flagEmoji('BS')),
  Country(name: 'Bahrain',                  code: 'BH', dialCode: '+973', phoneLength: 8,  flag: flagEmoji('BH')),
  Country(name: 'Bangladesh',               code: 'BD', dialCode: '+880', phoneLength: 10, flag: flagEmoji('BD')),
  Country(name: 'Belarus',                  code: 'BY', dialCode: '+375', phoneLength: 9,  flag: flagEmoji('BY')),
  Country(name: 'Belgium',                  code: 'BE', dialCode: '+32',  phoneLength: 9,  flag: flagEmoji('BE')),
  Country(name: 'Belize',                   code: 'BZ', dialCode: '+501', phoneLength: 7,  flag: flagEmoji('BZ')),
  Country(name: 'Benin',                    code: 'BJ', dialCode: '+229', phoneLength: 8,  flag: flagEmoji('BJ')),
  Country(name: 'Bhutan',                   code: 'BT', dialCode: '+975', phoneLength: 8,  flag: flagEmoji('BT')),
  Country(name: 'Bolivia',                  code: 'BO', dialCode: '+591', phoneLength: 8,  flag: flagEmoji('BO')),
  Country(name: 'Bosnia and Herzegovina',   code: 'BA', dialCode: '+387', phoneLength: 8,  flag: flagEmoji('BA')),
  Country(name: 'Botswana',                 code: 'BW', dialCode: '+267', phoneLength: 7,  flag: flagEmoji('BW')),
  Country(name: 'Brazil',                   code: 'BR', dialCode: '+55',  phoneLength: 11, flag: flagEmoji('BR')),
  Country(name: 'Brunei',                   code: 'BN', dialCode: '+673', phoneLength: 7,  flag: flagEmoji('BN')),
  Country(name: 'Bulgaria',                 code: 'BG', dialCode: '+359', phoneLength: 9,  flag: flagEmoji('BG')),
  Country(name: 'Burkina Faso',             code: 'BF', dialCode: '+226', phoneLength: 8,  flag: flagEmoji('BF')),
  Country(name: 'Burundi',                  code: 'BI', dialCode: '+257', phoneLength: 8,  flag: flagEmoji('BI')),
  Country(name: 'Cambodia',                 code: 'KH', dialCode: '+855', phoneLength: 9,  flag: flagEmoji('KH')),
  Country(name: 'Cameroon',                 code: 'CM', dialCode: '+237', phoneLength: 9,  flag: flagEmoji('CM')),
  Country(name: 'Canada',                   code: 'CA', dialCode: '+1',   phoneLength: 10, flag: flagEmoji('CA')),
  Country(name: 'Cape Verde',               code: 'CV', dialCode: '+238', phoneLength: 7,  flag: flagEmoji('CV')),
  Country(name: 'Central African Republic', code: 'CF', dialCode: '+236', phoneLength: 8,  flag: flagEmoji('CF')),
  Country(name: 'Chad',                     code: 'TD', dialCode: '+235', phoneLength: 8,  flag: flagEmoji('TD')),
  Country(name: 'Chile',                    code: 'CL', dialCode: '+56',  phoneLength: 9,  flag: flagEmoji('CL')),
  Country(name: 'China',                    code: 'CN', dialCode: '+86',  phoneLength: 11, flag: flagEmoji('CN')),
  Country(name: 'Colombia',                 code: 'CO', dialCode: '+57',  phoneLength: 10, flag: flagEmoji('CO')),
  Country(name: 'Comoros',                  code: 'KM', dialCode: '+269', phoneLength: 7,  flag: flagEmoji('KM')),
  Country(name: 'Congo',                    code: 'CG', dialCode: '+242', phoneLength: 9,  flag: flagEmoji('CG')),
  Country(name: 'Costa Rica',               code: 'CR', dialCode: '+506', phoneLength: 8,  flag: flagEmoji('CR')),
  Country(name: 'Croatia',                  code: 'HR', dialCode: '+385', phoneLength: 9,  flag: flagEmoji('HR')),
  Country(name: 'Cuba',                     code: 'CU', dialCode: '+53',  phoneLength: 8,  flag: flagEmoji('CU')),
  Country(name: 'Cyprus',                   code: 'CY', dialCode: '+357', phoneLength: 8,  flag: flagEmoji('CY')),
  Country(name: 'Czech Republic',           code: 'CZ', dialCode: '+420', phoneLength: 9,  flag: flagEmoji('CZ')),
  Country(name: 'Denmark',                  code: 'DK', dialCode: '+45',  phoneLength: 8,  flag: flagEmoji('DK')),
  Country(name: 'Djibouti',                 code: 'DJ', dialCode: '+253', phoneLength: 8,  flag: flagEmoji('DJ')),
  Country(name: 'Dominican Republic',       code: 'DO', dialCode: '+1',   phoneLength: 10, flag: flagEmoji('DO')),
  Country(name: 'DR Congo',                 code: 'CD', dialCode: '+243', phoneLength: 9,  flag: flagEmoji('CD')),
  Country(name: 'Ecuador',                  code: 'EC', dialCode: '+593', phoneLength: 9,  flag: flagEmoji('EC')),
  Country(name: 'Egypt',                    code: 'EG', dialCode: '+20',  phoneLength: 10, flag: flagEmoji('EG')),
  Country(name: 'El Salvador',              code: 'SV', dialCode: '+503', phoneLength: 8,  flag: flagEmoji('SV')),
  Country(name: 'Equatorial Guinea',        code: 'GQ', dialCode: '+240', phoneLength: 9,  flag: flagEmoji('GQ')),
  Country(name: 'Eritrea',                  code: 'ER', dialCode: '+291', phoneLength: 7,  flag: flagEmoji('ER')),
  Country(name: 'Estonia',                  code: 'EE', dialCode: '+372', phoneLength: 8,  flag: flagEmoji('EE')),
  Country(name: 'Ethiopia',                 code: 'ET', dialCode: '+251', phoneLength: 9,  flag: flagEmoji('ET')),
  Country(name: 'Fiji',                     code: 'FJ', dialCode: '+679', phoneLength: 7,  flag: flagEmoji('FJ')),
  Country(name: 'Finland',                  code: 'FI', dialCode: '+358', phoneLength: 9,  flag: flagEmoji('FI')),
  Country(name: 'France',                   code: 'FR', dialCode: '+33',  phoneLength: 9,  flag: flagEmoji('FR')),
  Country(name: 'Gabon',                    code: 'GA', dialCode: '+241', phoneLength: 7,  flag: flagEmoji('GA')),
  Country(name: 'Gambia',                   code: 'GM', dialCode: '+220', phoneLength: 7,  flag: flagEmoji('GM')),
  Country(name: 'Georgia',                  code: 'GE', dialCode: '+995', phoneLength: 9,  flag: flagEmoji('GE')),
  Country(name: 'Germany',                  code: 'DE', dialCode: '+49',  phoneLength: 10, flag: flagEmoji('DE')),
  Country(name: 'Ghana',                    code: 'GH', dialCode: '+233', phoneLength: 9,  flag: flagEmoji('GH')),
  Country(name: 'Greece',                   code: 'GR', dialCode: '+30',  phoneLength: 10, flag: flagEmoji('GR')),
  Country(name: 'Guatemala',                code: 'GT', dialCode: '+502', phoneLength: 8,  flag: flagEmoji('GT')),
  Country(name: 'Guinea',                   code: 'GN', dialCode: '+224', phoneLength: 9,  flag: flagEmoji('GN')),
  Country(name: 'Guinea-Bissau',            code: 'GW', dialCode: '+245', phoneLength: 7,  flag: flagEmoji('GW')),
  Country(name: 'Guyana',                   code: 'GY', dialCode: '+592', phoneLength: 7,  flag: flagEmoji('GY')),
  Country(name: 'Haiti',                    code: 'HT', dialCode: '+509', phoneLength: 8,  flag: flagEmoji('HT')),
  Country(name: 'Honduras',                 code: 'HN', dialCode: '+504', phoneLength: 8,  flag: flagEmoji('HN')),
  Country(name: 'Hungary',                  code: 'HU', dialCode: '+36',  phoneLength: 9,  flag: flagEmoji('HU')),
  Country(name: 'Iceland',                  code: 'IS', dialCode: '+354', phoneLength: 7,  flag: flagEmoji('IS')),
  Country(name: 'India',                    code: 'IN', dialCode: '+91',  phoneLength: 10, flag: flagEmoji('IN')),
  Country(name: 'Indonesia',                code: 'ID', dialCode: '+62',  phoneLength: 11, flag: flagEmoji('ID')),
  Country(name: 'Iran',                     code: 'IR', dialCode: '+98',  phoneLength: 10, flag: flagEmoji('IR')),
  Country(name: 'Iraq',                     code: 'IQ', dialCode: '+964', phoneLength: 10, flag: flagEmoji('IQ')),
  Country(name: 'Ireland',                  code: 'IE', dialCode: '+353', phoneLength: 9,  flag: flagEmoji('IE')),
  Country(name: 'Israel',                   code: 'IL', dialCode: '+972', phoneLength: 9,  flag: flagEmoji('IL')),
  Country(name: 'Italy',                    code: 'IT', dialCode: '+39',  phoneLength: 10, flag: flagEmoji('IT')),
  Country(name: 'Ivory Coast',              code: 'CI', dialCode: '+225', phoneLength: 8,  flag: flagEmoji('CI')),
  Country(name: 'Jamaica',                  code: 'JM', dialCode: '+1',   phoneLength: 10, flag: flagEmoji('JM')),
  Country(name: 'Japan',                    code: 'JP', dialCode: '+81',  phoneLength: 10, flag: flagEmoji('JP')),
  Country(name: 'Jordan',                   code: 'JO', dialCode: '+962', phoneLength: 9,  flag: flagEmoji('JO')),
  Country(name: 'Kazakhstan',               code: 'KZ', dialCode: '+7',   phoneLength: 10, flag: flagEmoji('KZ')),
  Country(name: 'Kenya',                    code: 'KE', dialCode: '+254', phoneLength: 9,  flag: flagEmoji('KE')),
  Country(name: 'Kuwait',                   code: 'KW', dialCode: '+965', phoneLength: 8,  flag: flagEmoji('KW')),
  Country(name: 'Kyrgyzstan',               code: 'KG', dialCode: '+996', phoneLength: 9,  flag: flagEmoji('KG')),
  Country(name: 'Laos',                     code: 'LA', dialCode: '+856', phoneLength: 9,  flag: flagEmoji('LA')),
  Country(name: 'Latvia',                   code: 'LV', dialCode: '+371', phoneLength: 8,  flag: flagEmoji('LV')),
  Country(name: 'Lebanon',                  code: 'LB', dialCode: '+961', phoneLength: 8,  flag: flagEmoji('LB')),
  Country(name: 'Lesotho',                  code: 'LS', dialCode: '+266', phoneLength: 8,  flag: flagEmoji('LS')),
  Country(name: 'Liberia',                  code: 'LR', dialCode: '+231', phoneLength: 7,  flag: flagEmoji('LR')),
  Country(name: 'Libya',                    code: 'LY', dialCode: '+218', phoneLength: 9,  flag: flagEmoji('LY')),
  Country(name: 'Liechtenstein',            code: 'LI', dialCode: '+423', phoneLength: 7,  flag: flagEmoji('LI')),
  Country(name: 'Lithuania',                code: 'LT', dialCode: '+370', phoneLength: 8,  flag: flagEmoji('LT')),
  Country(name: 'Luxembourg',               code: 'LU', dialCode: '+352', phoneLength: 9,  flag: flagEmoji('LU')),
  Country(name: 'Madagascar',               code: 'MG', dialCode: '+261', phoneLength: 9,  flag: flagEmoji('MG')),
  Country(name: 'Malawi',                   code: 'MW', dialCode: '+265', phoneLength: 9,  flag: flagEmoji('MW')),
  Country(name: 'Malaysia',                 code: 'MY', dialCode: '+60',  phoneLength: 10, flag: flagEmoji('MY')),
  Country(name: 'Maldives',                 code: 'MV', dialCode: '+960', phoneLength: 7,  flag: flagEmoji('MV')),
  Country(name: 'Mali',                     code: 'ML', dialCode: '+223', phoneLength: 8,  flag: flagEmoji('ML')),
  Country(name: 'Malta',                    code: 'MT', dialCode: '+356', phoneLength: 8,  flag: flagEmoji('MT')),
  Country(name: 'Mauritania',               code: 'MR', dialCode: '+222', phoneLength: 8,  flag: flagEmoji('MR')),
  Country(name: 'Mauritius',                code: 'MU', dialCode: '+230', phoneLength: 8,  flag: flagEmoji('MU')),
  Country(name: 'Mexico',                   code: 'MX', dialCode: '+52',  phoneLength: 10, flag: flagEmoji('MX')),
  Country(name: 'Moldova',                  code: 'MD', dialCode: '+373', phoneLength: 8,  flag: flagEmoji('MD')),
  Country(name: 'Monaco',                   code: 'MC', dialCode: '+377', phoneLength: 8,  flag: flagEmoji('MC')),
  Country(name: 'Mongolia',                 code: 'MN', dialCode: '+976', phoneLength: 8,  flag: flagEmoji('MN')),
  Country(name: 'Montenegro',               code: 'ME', dialCode: '+382', phoneLength: 8,  flag: flagEmoji('ME')),
  Country(name: 'Morocco',                  code: 'MA', dialCode: '+212', phoneLength: 9,  flag: flagEmoji('MA')),
  Country(name: 'Mozambique',               code: 'MZ', dialCode: '+258', phoneLength: 9,  flag: flagEmoji('MZ')),
  Country(name: 'Myanmar',                  code: 'MM', dialCode: '+95',  phoneLength: 9,  flag: flagEmoji('MM')),
  Country(name: 'Namibia',                  code: 'NA', dialCode: '+264', phoneLength: 9,  flag: flagEmoji('NA')),
  Country(name: 'Nepal',                    code: 'NP', dialCode: '+977', phoneLength: 10, flag: flagEmoji('NP')),
  Country(name: 'Netherlands',              code: 'NL', dialCode: '+31',  phoneLength: 9,  flag: flagEmoji('NL')),
  Country(name: 'New Zealand',              code: 'NZ', dialCode: '+64',  phoneLength: 9,  flag: flagEmoji('NZ')),
  Country(name: 'Nicaragua',                code: 'NI', dialCode: '+505', phoneLength: 8,  flag: flagEmoji('NI')),
  Country(name: 'Niger',                    code: 'NE', dialCode: '+227', phoneLength: 8,  flag: flagEmoji('NE')),
  Country(name: 'Nigeria',                  code: 'NG', dialCode: '+234', phoneLength: 10, flag: flagEmoji('NG')),
  Country(name: 'North Korea',              code: 'KP', dialCode: '+850', phoneLength: 10, flag: flagEmoji('KP')),
  Country(name: 'North Macedonia',          code: 'MK', dialCode: '+389', phoneLength: 8,  flag: flagEmoji('MK')),
  Country(name: 'Norway',                   code: 'NO', dialCode: '+47',  phoneLength: 8,  flag: flagEmoji('NO')),
  Country(name: 'Oman',                     code: 'OM', dialCode: '+968', phoneLength: 8,  flag: flagEmoji('OM')),
  Country(name: 'Pakistan',                 code: 'PK', dialCode: '+92',  phoneLength: 10, flag: flagEmoji('PK')),
  Country(name: 'Panama',                   code: 'PA', dialCode: '+507', phoneLength: 8,  flag: flagEmoji('PA')),
  Country(name: 'Papua New Guinea',         code: 'PG', dialCode: '+675', phoneLength: 8,  flag: flagEmoji('PG')),
  Country(name: 'Paraguay',                 code: 'PY', dialCode: '+595', phoneLength: 9,  flag: flagEmoji('PY')),
  Country(name: 'Peru',                     code: 'PE', dialCode: '+51',  phoneLength: 9,  flag: flagEmoji('PE')),
  Country(name: 'Philippines',              code: 'PH', dialCode: '+63',  phoneLength: 10, flag: flagEmoji('PH')),
  Country(name: 'Poland',                   code: 'PL', dialCode: '+48',  phoneLength: 9,  flag: flagEmoji('PL')),
  Country(name: 'Portugal',                 code: 'PT', dialCode: '+351', phoneLength: 9,  flag: flagEmoji('PT')),
  Country(name: 'Qatar',                    code: 'QA', dialCode: '+974', phoneLength: 8,  flag: flagEmoji('QA')),
  Country(name: 'Romania',                  code: 'RO', dialCode: '+40',  phoneLength: 9,  flag: flagEmoji('RO')),
  Country(name: 'Russia',                   code: 'RU', dialCode: '+7',   phoneLength: 10, flag: flagEmoji('RU')),
  Country(name: 'Rwanda',                   code: 'RW', dialCode: '+250', phoneLength: 9,  flag: flagEmoji('RW')),
  Country(name: 'Saudi Arabia',             code: 'SA', dialCode: '+966', phoneLength: 9,  flag: flagEmoji('SA')),
  Country(name: 'Senegal',                  code: 'SN', dialCode: '+221', phoneLength: 9,  flag: flagEmoji('SN')),
  Country(name: 'Serbia',                   code: 'RS', dialCode: '+381', phoneLength: 9,  flag: flagEmoji('RS')),
  Country(name: 'Sierra Leone',             code: 'SL', dialCode: '+232', phoneLength: 8,  flag: flagEmoji('SL')),
  Country(name: 'Singapore',                code: 'SG', dialCode: '+65',  phoneLength: 8,  flag: flagEmoji('SG')),
  Country(name: 'Slovakia',                 code: 'SK', dialCode: '+421', phoneLength: 9,  flag: flagEmoji('SK')),
  Country(name: 'Slovenia',                 code: 'SI', dialCode: '+386', phoneLength: 8,  flag: flagEmoji('SI')),
  Country(name: 'Somalia',                  code: 'SO', dialCode: '+252', phoneLength: 8,  flag: flagEmoji('SO')),
  Country(name: 'South Africa',             code: 'ZA', dialCode: '+27',  phoneLength: 9,  flag: flagEmoji('ZA')),
  Country(name: 'South Korea',              code: 'KR', dialCode: '+82',  phoneLength: 10, flag: flagEmoji('KR')),
  Country(name: 'South Sudan',              code: 'SS', dialCode: '+211', phoneLength: 9,  flag: flagEmoji('SS')),
  Country(name: 'Spain',                    code: 'ES', dialCode: '+34',  phoneLength: 9,  flag: flagEmoji('ES')),
  Country(name: 'Sri Lanka',                code: 'LK', dialCode: '+94',  phoneLength: 9,  flag: flagEmoji('LK')),
  Country(name: 'Sudan',                    code: 'SD', dialCode: '+249', phoneLength: 9,  flag: flagEmoji('SD')),
  Country(name: 'Suriname',                 code: 'SR', dialCode: '+597', phoneLength: 7,  flag: flagEmoji('SR')),
  Country(name: 'Sweden',                   code: 'SE', dialCode: '+46',  phoneLength: 9,  flag: flagEmoji('SE')),
  Country(name: 'Switzerland',              code: 'CH', dialCode: '+41',  phoneLength: 9,  flag: flagEmoji('CH')),
  Country(name: 'Syria',                    code: 'SY', dialCode: '+963', phoneLength: 9,  flag: flagEmoji('SY')),
  Country(name: 'Taiwan',                   code: 'TW', dialCode: '+886', phoneLength: 9,  flag: flagEmoji('TW')),
  Country(name: 'Tajikistan',               code: 'TJ', dialCode: '+992', phoneLength: 9,  flag: flagEmoji('TJ')),
  Country(name: 'Tanzania',                 code: 'TZ', dialCode: '+255', phoneLength: 9,  flag: flagEmoji('TZ')),
  Country(name: 'Thailand',                 code: 'TH', dialCode: '+66',  phoneLength: 9,  flag: flagEmoji('TH')),
  Country(name: 'Timor-Leste',              code: 'TL', dialCode: '+670', phoneLength: 8,  flag: flagEmoji('TL')),
  Country(name: 'Togo',                     code: 'TG', dialCode: '+228', phoneLength: 8,  flag: flagEmoji('TG')),
  Country(name: 'Trinidad and Tobago',      code: 'TT', dialCode: '+1',   phoneLength: 10, flag: flagEmoji('TT')),
  Country(name: 'Tunisia',                  code: 'TN', dialCode: '+216', phoneLength: 8,  flag: flagEmoji('TN')),
  Country(name: 'Turkey',                   code: 'TR', dialCode: '+90',  phoneLength: 10, flag: flagEmoji('TR')),
  Country(name: 'Turkmenistan',             code: 'TM', dialCode: '+993', phoneLength: 8,  flag: flagEmoji('TM')),
  Country(name: 'Uganda',                   code: 'UG', dialCode: '+256', phoneLength: 9,  flag: flagEmoji('UG')),
  Country(name: 'Ukraine',                  code: 'UA', dialCode: '+380', phoneLength: 9,  flag: flagEmoji('UA')),
  Country(name: 'United Arab Emirates',     code: 'AE', dialCode: '+971', phoneLength: 9,  flag: flagEmoji('AE')),
  Country(name: 'United Kingdom',           code: 'GB', dialCode: '+44',  phoneLength: 10, flag: flagEmoji('GB')),
  Country(name: 'United States',            code: 'US', dialCode: '+1',   phoneLength: 10, flag: flagEmoji('US')),
  Country(name: 'Uruguay',                  code: 'UY', dialCode: '+598', phoneLength: 8,  flag: flagEmoji('UY')),
  Country(name: 'Uzbekistan',               code: 'UZ', dialCode: '+998', phoneLength: 9,  flag: flagEmoji('UZ')),
  Country(name: 'Venezuela',                code: 'VE', dialCode: '+58',  phoneLength: 10, flag: flagEmoji('VE')),
  Country(name: 'Vietnam',                  code: 'VN', dialCode: '+84',  phoneLength: 9,  flag: flagEmoji('VN')),
  Country(name: 'Yemen',                    code: 'YE', dialCode: '+967', phoneLength: 9,  flag: flagEmoji('YE')),
  Country(name: 'Zambia',                   code: 'ZM', dialCode: '+260', phoneLength: 9,  flag: flagEmoji('ZM')),
  Country(name: 'Zimbabwe',                 code: 'ZW', dialCode: '+263', phoneLength: 9,  flag: flagEmoji('ZW')),
];